### ISSUE TITLE
Gem::GemNotFoundException when running pdk gem on Alpine Linux v3.13.5 

### ISSUE THREAD

**Issue by sanfrancrisko** [puppetlabs/pdk#1097]
Hello,

I hope it is OK to revive this issue. We're trying to run pdk in an Alpine Linux v3.13.5 container with ruby version 2.7.3 and PDK version 2.1.0 and we're getting the same error as the original poster of the issue.  PDK was installed as a ruby gem.

Does anyone have any suggestion why it might be failing? Thanks!

```
pdk validate
pdk (WARN): This module is compatible with an older version of PDK. Run `pdk update` to update it to your version of PDK.
pdk (INFO): Using Ruby 2.7.3
pdk (INFO): Using Puppet 6.22.1
pdk (INFO): Running all available validators...
[✖] Resolving default Gemfile dependencies.
pdk (FATAL):
/usr/lib/ruby/2.7.0/rubygems.rb:277:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
        from /usr/lib/ruby/2.7.0/rubygems.rb:296:in `activate_bin_path'
        from /usr/bin/bundle:23:in `<main>'

pdk (FATAL): Unable to resolve default Gemfile dependencies.
```

_Originally posted by @anders-larsson in https://github.com/puppetlabs/pdk/issues/914#issuecomment-863066878_

**Comment by sanfrancrisko** [comment]
Hi @anders-larsson, I've created a separate issue to track the problem you reported in https://github.com/puppetlabs/pdk/issues/914#issuecomment-863066878.

I've been able to reproduce this issue on the latest version of Alpine with Ruby 2.7.3 - we'll take a look in to it. Thanks for the info about the environment you included.
