### ISSUE TITLE
`screen_view': wrong number of arguments (given 2, expected 1) (ArgumentError)

### ISSUE THREAD

**Issue by duritong** [puppetlabs/pdk#1171]
Just did `gem install pdk` and tried to run `pdk new module foo`and *bam*:

```
$ pdk new module foo
/home/duritong/.local/share/gem/ruby/gems/pdk-2.4.0/lib/pdk/analytics/client/noop.rb:13:in `screen_view': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from /home/duritong/.local/share/gem/ruby/gems/pdk-2.4.0/lib/pdk/cli/util.rb:300:in `analytics_screen_view'
	from /home/duritong/.local/share/gem/ruby/gems/pdk-2.4.0/lib/pdk/cli/new/module.rb:24:in `block (2 levels) in <module:CLI>'
	from /home/duritong/.local/share/gem/ruby/gems/cri-2.15.11/lib/cri/command.rb:362:in `run_this'
	from /home/duritong/.local/share/gem/ruby/gems/cri-2.15.11/lib/cri/command.rb:298:in `run'
	from /home/duritong/.local/share/gem/ruby/gems/cri-2.15.11/lib/cri/command.rb:316:in `run'
	from /home/duritong/.local/share/gem/ruby/gems/cri-2.15.11/lib/cri/command.rb:316:in `run'
	from /home/duritong/.local/share/gem/ruby/gems/pdk-2.4.0/lib/pdk/cli.rb:71:in `run'
	from /home/duritong/.local/share/gem/ruby/gems/pdk-2.4.0/exe/pdk:6:in `<top (required)>'
	from /home/duritong/.local/share/gem/ruby/bin/pdk:23:in `load'
	from /home/duritong/.local/share/gem/ruby/bin/pdk:23:in `<main>'

$ gem info pdk

*** LOCAL GEMS ***

pdk (2.4.0)
    Author: Puppet, Inc.
    Homepage: https://github.com/puppetlabs/pdk
    Installed at: /home/duritong/.local/share/gem/ruby

    A key part of the Puppet Development Kit, the shortest path to
    better modules

$ ruby -v
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]
```

**Comment by jbh** [comment]
I'm having the exact same issue out of nowhere... pdk was working fine yesterday, but today... I suddenly get the same error.

```
$ pdk test unit
/home/yesh/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/pdk-2.5.0/lib/pdk/analytics/client/noop.rb:13:in `screen_view': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from /home/yesh/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/pdk-2.5.0/lib/pdk/cli/util.rb:300:in `analytics_screen_view'
	from /home/yesh/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/pdk-2.5.0/lib/pdk/cli/test/unit.rb:36:in `block (2 levels) in <module:CLI>'
	from /home/yesh/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cri-2.15.11/lib/cri/command.rb:362:in `run_this'
	from /home/yesh/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cri-2.15.11/lib/cri/command.rb:298:in `run'
	from /home/yesh/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cri-2.15.11/lib/cri/command.rb:316:in `run'
	from /home/yesh/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cri-2.15.11/lib/cri/command.rb:316:in `run'
	from /home/yesh/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/pdk-2.5.0/lib/pdk/cli.rb:71:in `run'
	from /home/yesh/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/pdk-2.5.0/exe/pdk:6:in `<top (required)>'
	from /home/yesh/.rbenv/versions/3.1.2/bin/pdk:25:in `load'
	from /home/yesh/.rbenv/versions/3.1.2/bin/pdk:25:in `<main>'
```

**Comment by jbh** [comment]
I reverted back to ruby 2.7.6 for now, and pdk 2.5 is working fine there.

**Comment by buzzdeee** [comment]
hit the same with Ruby 3.1 and pdk 2.6.1 on OpenBSD.

**Comment by chelnak** [comment]
Hey everyone! 

Right now the highest Ruby that PDK officially supports is 2.7.7. 

If you are using the gem over the package I'd recommend using something like rvenv/rvm if possible.

Support for Ruby 3 is in the works.

**Comment by david22swan** [comment]
Closing this as Ruby 3 support has been released.
Please reopen if the issue persists.
