### ISSUE TITLE
`pdk update` to 2.7.0 fails on could not find compatible gems 

### ISSUE THREAD

**Issue by ardrigh** [puppetlabs/pdk#1231]
**Describe the bug**
We currently have a number of modules using PDK 2.6.1
We attempted to update a module to 2.7.0 and `pdk update` failed.

```shell
> pdk update
pdk (INFO): Updating private-module using the default template, from tags/2.7.1 to 2.7.2

----------Files to be modified----------
/home/user/private-module/metadata.json
/home/user/private-module/Gemfile

----------------------------------------

You can find a report of differences in update_report.txt.

Do you want to continue and make these changes to your module? Yes
pdk (FATAL): Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Resolving dependencies...

Bundler could not find compatible versions for gem "puppet-lint":
  In Gemfile:
    puppet-lint-legacy_facts-check was resolved to 1.0.2, which depends on
      puppet-lint (~> 2.0)

    voxpupuli-puppet-lint-plugins (~> 4.0) was resolved to 4.0.0, which depends on
      puppet-lint (~> 3.1)
Bundler could not find compatible versions for gem "r10k":
  In Gemfile:
    puppet_litmus (< 1.0.0) ruby, x64_mingw was resolved to 0.34.6, which depends on
      bolt (~> 3.0) was resolved to 3.27.1, which depends on
        r10k (~> 3.10)

    puppet_litmus (< 1.0.0) ruby, x64_mingw was resolved to 0.34.6, which depends on
      r10k (= 3.15.1)
Bundler could not find compatible versions for gem "rubocop":
  In Gemfile:
    rubocop (= 1.6.1)

    rubocop-performance (= 1.9.1) was resolved to 1.9.1, which depends on
      rubocop (>= 0.90.0, < 2.0)

    rubocop-rspec (= 2.0.1) was resolved to 2.0.1, which depends on
      rubocop (~> 1.0)

pdk (FATAL): Unable to resolve Gemfile dependencies.
```

**To Reproduce**
Run `pdk update` on a module using PDK 2.6.1

**Expected behavior**
PDK would use the correct gem versions and not fail on dependencies.

**Additional context**
Installed `pdk-2.7.0.0-1.fc36.x86_64` using RPM from `puppet-tools-release-1.0.0-9.fc36.noarch`, running on Fedora 37.
Have had no issues upgrading previous releases of PDK, especially not this bad.

Prior to running `pdk update` trying to run `pdk test unit` failed on Rakefile errors

```shell
pdk test unit
pdk (WARN): This module is compatible with an older version of PDK. Run `pdk update` to update it to your version of PDK.
pdk (INFO): Using Ruby 2.7.7
pdk (INFO): Using Puppet 7.23.0
[✖] Preparing to run the unit tests.
[✖] Cleaning up after running unit tests.
pdk (ERROR): The spec_clean rake task failed with the following error(s):

rake aborted!
LoadError: cannot load such file -- puppet_blacksmith/rake_tasks
/home/user/private-module/Rakefile:7:in `require'
/home/user/private-module/Rakefile:7:in `<top (required)>'
/opt/puppetlabs/pdk/share/cache/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)

pdk (FATAL): Failed to clean up after running unit tests```

**Comment by ardrigh** [comment]
Additional bit of context on the `spec_clean` error from running `pdk test unit --debug`

```
pdk (ERROR): The spec_clean rake task failed with the following error(s):

rake aborted!
LoadError: cannot load such file -- puppet_blacksmith/rake_tasks
/home/user/private-module/Rakefile:7:in `require'
/home/user/private-module/Rakefile:7:in `<top (required)>'
/opt/puppetlabs/pdk/share/cache/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)

pdk (FATAL): Failed to clean up after running unit tests
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.7.7/lib/ruby/gems/2.7.0/gems/pdk-2.7.0/lib/pdk/tests/unit.rb:60:in `print_failure'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.7.7/lib/ruby/gems/2.7.0/gems/pdk-2.7.0/lib/pdk/tests/unit.rb:69:in `tear_down'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.7.7/lib/ruby/gems/2.7.0/gems/pdk-2.7.0/lib/pdk/tests/unit.rb:77:in `setup'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.7.7/lib/ruby/gems/2.7.0/gems/pdk-2.7.0/lib/pdk/tests/unit.rb:89:in `invoke'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.7.7/lib/ruby/gems/2.7.0/gems/pdk-2.7.0/lib/pdk/cli/test/unit.rb:80:in `block (2 levels) in <module:CLI>'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.7.7/lib/ruby/gems/2.7.0/gems/cri-2.15.11/lib/cri/command.rb:362:in `run_this'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.7.7/lib/ruby/gems/2.7.0/gems/cri-2.15.11/lib/cri/command.rb:298:in `run'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.7.7/lib/ruby/gems/2.7.0/gems/cri-2.15.11/lib/cri/command.rb:316:in `run'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.7.7/lib/ruby/gems/2.7.0/gems/cri-2.15.11/lib/cri/command.rb:316:in `run'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.7.7/lib/ruby/gems/2.7.0/gems/pdk-2.7.0/lib/pdk/cli.rb:55:in `run'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.7.7/lib/ruby/gems/2.7.0/gems/pdk-2.7.0/exe/pdk:6:in `<top (required)>'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.7.7/bin/pdk:23:in `load'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.7.7/bin/pdk:23:in `<main>'
```

**Comment by ardrigh** [comment]
One suggestion provided on Slack was to `rm -rf ~/.pdk/cache/ruby` and running that command resolved the error related to `puppet_blacksmith`.

However the main error on Gem versions still remains

**Comment by ardrigh** [comment]
If I change the Puppet version requirement in `metadata.json` I get a different set of gems listed

```
 pdk validate
pdk (INFO): Using Ruby 2.5.9
pdk (INFO): Using Puppet 6.29.0
pdk (INFO): Running all available validators...
pdk (FATAL): Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies........
Resolving dependencies.......

Bundler found conflicting requirements for the Ruby version:
  In Gemfile:
    puppet_litmus (< 1.0.0) ruby, x64_mingw was resolved to 0.34.6, which depends on
      bolt (~> 3.0) was resolved to 3.27.1, which depends on
        net-ssh (>= 4.0, < 8.0) was resolved to 7.1.0, which depends on
          Ruby (>= 2.6)

  Current Ruby version:
    Ruby (= 2.5.9)

Bundler could not find compatible versions for gem "net-ssh":
  In Gemfile:
    puppet_litmus (< 1.0.0) ruby, x64_mingw was resolved to 0.34.6, which depends on
      bolt (~> 3.0) was resolved to 3.27.1, which depends on
        net-ssh (>= 4.0, < 8.0)

    serverspec (~> 2.41) was resolved to 2.42.2, which depends on
      specinfra (~> 2.72) was resolved to 2.85.0, which depends on
        net-ssh (>= 2.7)
Bundler could not find compatible versions for gem "puppet":
  In Gemfile:
    puppet (= 6.29.0)

    puppet_litmus (< 1.0.0) ruby, x64_mingw was resolved to 0.34.6, which depends on
      bolt (~> 3.0) was resolved to 3.27.1, which depends on
        puppet (>= 6.18.0)

    puppet-debugger (~> 1.0) was resolved to 1.3.0, which depends on
      puppet (>= 5.5)

    rspec-puppet-facts (~> 2.0) was resolved to 2.0.5, which depends on
      puppet
Bundler could not find compatible versions for gem "puppet-lint":
  In Gemfile:
    puppet-lint-legacy_facts-check was resolved to 1.0.2, which depends on
      puppet-lint (~> 2.0)

    voxpupuli-puppet-lint-plugins (~> 4.0) was resolved to 4.0.0, which depends on
      puppet-lint (~> 3.1)
Bundler could not find compatible versions for gem "r10k":
  In Gemfile:
    puppet_litmus (< 1.0.0) ruby, x64_mingw was resolved to 0.34.6, which depends on
      bolt (~> 3.0) was resolved to 3.27.1, which depends on
        r10k (~> 3.10)

    puppet_litmus (< 1.0.0) ruby, x64_mingw was resolved to 0.34.6, which depends on
      r10k (= 3.15.1)
Bundler could not find compatible versions for gem "rubocop":
  In Gemfile:
    rubocop (= 1.6.1)

    rubocop-performance (= 1.9.1) was resolved to 1.9.1, which depends on
      rubocop (>= 0.90.0, < 2.0)

    rubocop-rspec (= 2.0.1) was resolved to 2.0.1, which depends on
      rubocop (~> 1.0)

pdk (FATAL): Unable to resolve Gemfile dependencies.
```

**Comment by chelnak** [comment]
Hey @ardrigh. Thanks for the heads up. 

I'm looking in to this.

**Comment by chelnak** [comment]
I notice that you are using fedora 37 in your example. Would you be able to re test on fedora 36?

There shouldn't be any major differences but we don't actually build a PDK package for fedora 37 right now... and I just want to get that ticked off the list.

Additionally, is the module you are upgrading open source? It would be good to use as a reference when running some tests.

**Comment by ardrigh** [comment]
I can create a container to test in Fedora 36. The module I was upgrading is private so I can't share it, but I test if it behaves the same on a new+updated module.

**Comment by ardrigh** [comment]
Still get errors if I run in Fedora 36 container

```shell
# pdk update
pdk (INFO): Updating user-private_module using the default template, from tags/2.7.2 to 2.7.2

------------Files to be added-----------
/mnt/private_module/Gemfile

----------------------------------------
Do you want to continue and make these changes to your module? Yes
pdk (FATAL): Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Resolving dependencies...

Bundler could not find compatible versions for gem "puppet-lint":
  In Gemfile:
    puppet-lint-legacy_facts-check was resolved to 1.0.2, which depends on
      puppet-lint (~> 2.0)

    voxpupuli-puppet-lint-plugins (~> 4.0) was resolved to 4.0.0, which depends on
      puppet-lint (~> 3.1)
Bundler could not find compatible versions for gem "r10k":
  In Gemfile:
    puppet_litmus (< 1.0.0) ruby, x64_mingw was resolved to 0.34.6, which depends on
      bolt (~> 3.0) was resolved to 3.27.1, which depends on
        r10k (~> 3.10)

    puppet_litmus (< 1.0.0) ruby, x64_mingw was resolved to 0.34.6, which depends on
      r10k (= 3.15.1)
Bundler could not find compatible versions for gem "rubocop":
  In Gemfile:
    rubocop (= 1.6.1)

    rubocop-performance (= 1.9.1) was resolved to 1.9.1, which depends on
      rubocop (>= 0.90.0, < 2.0)

    rubocop-rspec (= 2.0.1) was resolved to 2.0.1, which depends on
      rubocop (~> 1.0)

pdk (FATAL): Unable to resolve Gemfile dependencies.
```

**Comment by ardrigh** [comment]
If it helps this is the `metadata.json` file content

```shell
# cat metadata.json
{
  "name": "user-private_module",
  "version": "1.0.0",
  "author": "User",
  "summary": "Manage the configuration for software used within business",
  "license": "Apache-2.0",
  "dependencies": [
    {
      "name": "puppetlabs-stdlib",
      "version_requirement": ">= 7.0.0 < 9.0.0"
    }
  ],
  "operatingsystem_support": [
    {
      "operatingsystem": "CentOS",
      "operatingsystemrelease": [
        "7"
      ]
    },
    {
      "operatingsystem": "RedHat",
      "operatingsystemrelease": [
        "8"
      ]
    }
  ],
  "requirements": [
    {
      "name": "puppet",
      "version_requirement": ">= 6.0.0 < 8.0.0"
    }
  ],
  "pdk-version": "2.7.0",
  "template-url": "pdk-default#2.7.2",
  "template-ref": "tags/2.7.2-0-g3f1215d"
}```

**Comment by chelnak** [comment]
Metadata looks fine to me.

Do you have disable_legacy_facts enabled in your sync file?

**Comment by ardrigh** [comment]
I have removed the line for `disable_legacy_facts` and now the errors have gone.

It appears changes have been made to the templates here https://github.com/puppetlabs/pdk-templates/pull/502

**Comment by chelnak** [comment]
Great! Glad this is resolved for you now.
