### ISSUE TITLE
facter_implementation missing?

### ISSUE THREAD

**Issue by ardrigh** [puppetlabs/pdk#1238]
**Describe the bug**
I was reading documentation to see what options PDK might have to help speed up some of our workflow.

I read in the documentation there is an option to change `facter_implementation`

https://github.com/puppetlabs/pdk-templates/blob/main/README.md#specspec_helperrb
https://github.com/puppetlabs/rspec-puppet#facter_implementation

I added the line to `.sync.yml`:

```yaml
spec/spec_helper.rb:
  coverage_report: true
  facter_implementation: 'rspec'
```

Then ran `pdk update`:

```ruby
 RSpec.configure do |c|
   c.default_facts = default_facts
+  c.facter_implementation = rspec
```

I tried to run a test and it failed:

```shell
An error occurred while loading ./spec/classes/foo_spec.rb.
Failure/Error: c.facter_implementation = rspec

NameError:
  undefined local variable or method `rspec' for main:Object
# ./spec/spec_helper.rb:41:in `block in <top (required)>'
# ./spec/spec_helper.rb:39:in `<top (required)>'
```

Is there something missing from the PDK install?

**To Reproduce**
Follow steps above

**Expected behavior**
Unit tests would run using the faster `rspec` implementation as documented

**Additional context**
- Using `pdk-2.7.1.0-1.fc36.x86_64` rpm package on Fedora 37

**Comment by ardrigh** [comment]
I created a PR for pdk-templates to fix this error
