### ISSUE TITLE
Can't create module if new module fails to get login

### ISSUE THREAD

**Issue by garethr** [puppetlabs/pdk#157]
I managed to trigger the following exception when running `pdk new module`, in my case when running under root on Debian.

```ruby
pdk (INFO): Creating new module: something
/usr/local/bundle/gems/pdk-0.4.1/lib/pdk/generators/module.rb:58:in `username_from_login': undefined method `gsub' for nil:NilClass (NoMethodError)
        from /usr/local/bundle/gems/pdk-0.4.1/lib/pdk/generators/module.rb:71:in `prepare_metadata'
        from /usr/local/bundle/gems/pdk-0.4.1/lib/pdk/generators/module.rb:27:in `invoke'
        from /usr/local/bundle/gems/pdk-0.4.1/lib/pdk/cli/new/module.rb:41:in `block (2 levels) in <module:CLI>'
        from /usr/local/bundle/gems/cri-2.9.1/lib/cri/command.rb:319:in `run_this'
        from /usr/local/bundle/gems/cri-2.9.1/lib/cri/command.rb:264:in `run'
        from /usr/local/bundle/gems/cri-2.9.1/lib/cri/command.rb:282:in `run'
        from /usr/local/bundle/gems/cri-2.9.1/lib/cri/command.rb:282:in `run'
        from /usr/local/bundle/gems/pdk-0.4.1/lib/pdk/cli.rb:15:in `run'
        from /usr/local/bundle/gems/pdk-0.4.1/exe/pdk:5:in `<top (required)>'
        from /usr/local/bundle/bin/pdk:22:in `load'
        from /usr/local/bundle/bin/pdk:22:in `<main>'
```

Note that `getlogin`:

```
Returns the short user name of the currently logged in user.
Unfortunately, it is often rather easy to fool ::getlogin.
```

From https://github.com/ruby/ruby/blob/202bbda2bf5f25343e286099140fb9282880ecba/ext/etc/etc.c#L60

Reading the source, it suggests falling back to getpwuid. On the same host as above:

```ruby
> require 'etc'
=> true
> Etc.getlogin
=> nil
> Etc.getpwuid
=> #<struct Etc::Passwd name="root", passwd="x", uid=0, gid=0, gecos="root", dir="/root", shell="/bin/bash">
> Etc.getpwuid.name
=> "root"
```

Login ends up as nil here: https://github.com/puppetlabs/pdk/blob/master/lib/pdk/generators/module.rb#L57

As a side note, I didn't see a way of overriding this value? For instance if releasing modules under multiple namespaces, or working on computers where usernames are corporate controlled. I didn't see anything in `--help`. Happy to open a separate issue on that if useful.

**Comment by DavidS** [comment]
Fixed in #160
