### ISSUE TITLE
convert fails non-latest Puppet version

### ISSUE THREAD

**Issue by jeremy-asher** [puppetlabs/pdk#399]
The `pdk convert` command crashes when using versions of Puppet other than the latest.

I'm not aware if there is an alternative way to set the Puppet version when using PDK, but I have been using the standard environment variable.  For example:

```
[root@4e57747fe881 ntp]# export PUPPET_GEM_VERSION=5.3.2
```

This results in a crash when using `pdk convert` due to the cached `Gemfile.lock` which is currently built using Puppet 5.3.3.  This could probably fixed with a `bundle update` instead of a `bundle install`.

<details>
<summary>pdk convert crash (running against the NTP module)</summary>

```
[root@4e57747fe881 ntp]# pdk convert --debug
pdk (DEBUG): Using 'private/git/bin/git' from PDK package.
pdk (DEBUG): Using 'private/git/bin/git' from PDK package.
pdk (DEBUG): Executing '/opt/puppetlabs/pdk/private/git/bin/git clone file:///opt/puppetlabs/pdk/share/cache/pdk-templates.git /tmp/pdk-templates20171221-1393-1cpjebe'
pdk (DEBUG): Execution of '/opt/puppetlabs/pdk/private/git/bin/git clone file:///opt/puppetlabs/pdk/share/cache/pdk-templates.git /tmp/pdk-templates20171221-1393-1cpjebe' complete (duration: 0.084376892s; exit code: 0)
pdk (DEBUG): Using 'private/git/bin/git' from PDK package.
pdk (DEBUG): Using 'private/git/bin/git' from PDK package.
pdk (DEBUG): Executing '/opt/puppetlabs/pdk/private/git/bin/git -C /tmp/pdk-templates20171221-1393-1cpjebe reset --hard 1.3.0'
pdk (DEBUG): Execution of '/opt/puppetlabs/pdk/private/git/bin/git -C /tmp/pdk-templates20171221-1393-1cpjebe reset --hard 1.3.0' complete (duration: 0.006936146s; exit code: 0)
pdk (DEBUG): Using 'private/git/bin/git' from PDK package.
pdk (DEBUG): Using 'private/git/bin/git' from PDK package.
pdk (DEBUG): Executing '/opt/puppetlabs/pdk/private/git/bin/git --git-dir /tmp/pdk-templates20171221-1393-1cpjebe/.git describe --all --long --always'
pdk (DEBUG): Execution of '/opt/puppetlabs/pdk/private/git/bin/git --git-dir /tmp/pdk-templates20171221-1393-1cpjebe/.git describe --all --long --always' complete (duration: 0.003530898s; exit code: 0)
pdk (DEBUG): Rendering '.gitlab-ci.yml.erb'...
pdk (DEBUG): Rendering 'Rakefile.erb'...
pdk (DEBUG): Rendering '.rubocop.yml.erb'...
pdk (DEBUG): Rendering 'spec/spec_helper.rb.erb'...
pdk (DEBUG): Rendering 'spec/default_facts.yml.erb'...
pdk (DEBUG): Rendering '.gitignore.erb'...
pdk (DEBUG): Rendering '.rspec.erb'...
pdk (DEBUG): Rendering 'Gemfile.erb'...
pdk (DEBUG): Rendering '.travis.yml.erb'...
pdk (DEBUG): Rendering '.pmtignore.erb'...
pdk (DEBUG): Rendering 'appveyor.yml.erb'...
pdk (DEBUG): Rendering '.yardopts.erb'...

------------Files to be added-----------
.gitlab-ci.yml
.rubocop.yml
spec/default_facts.yml
.gitignore
.rspec
.travis.yml
.pmtignore
appveyor.yml
.yardopts

----------Files to be modified----------
metadata.json
Rakefile
spec/spec_helper.rb
Gemfile

----------------------------------------

You can find a report of differences in convert_report.txt.

pdk (INFO): Module conversion is a potentially destructive action. Ensure that you have committed your module to a version control system or have a backup, and review the changes above before continuing.
Do you want to continue and make these changes to your module? Yes
pdk (DEBUG): No Gemfile.lock found in module. Using vendored Gemfile.lock from '/opt/puppetlabs/pdk/share/cache/Gemfile.lock'.
pdk (DEBUG): Checking for missing Gemfile dependencies.
pdk (DEBUG): Using 'private/ruby/2.1.9/bin/bundle' from PDK package.
pdk (DEBUG): Executing '/opt/puppetlabs/pdk/private/ruby/2.1.9/bin/bundle check --gemfile=/tmp/ntp/Gemfile'
pdk (DEBUG): Command environment: GEM_HOME is '/root/.pdk/cache/ruby/2.1.0' and GEM_PATH is '/opt/puppetlabs/pdk/share/cache/ruby/2.1.0'
pdk (DEBUG): Execution of '/opt/puppetlabs/pdk/private/ruby/2.1.9/bin/bundle check --gemfile=/tmp/ntp/Gemfile' complete (duration: 0.758601771s; exit code: 1)
pdk (DEBUG): Bundler can't satisfy your Gemfile's dependencies.
Install missing gems with `bundle install`.


pdk (DEBUG): Using 'private/ruby/2.1.9/bin/bundle' from PDK package.
pdk (DEBUG): Executing '/opt/puppetlabs/pdk/private/ruby/2.1.9/bin/bundle install --gemfile=/tmp/ntp/Gemfile -j4'
pdk (DEBUG): Command environment: GEM_HOME is '/root/.pdk/cache/ruby/2.1.0' and GEM_PATH is '/opt/puppetlabs/pdk/share/cache/ruby/2.1.0'
pdk (DEBUG): Execution of '/opt/puppetlabs/pdk/private/ruby/2.1.9/bin/bundle install --gemfile=/tmp/ntp/Gemfile -j4' complete (duration: 3.794491592s; exit code: 7)
pdk (FATAL): The dependency puppet-module-win-default-r2.1 (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mswin32, x86-mingw32, x64-mingw32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mswin32 x86-mingw32 x64-mingw32`.
The dependency puppet-module-win-dev-r2.1 (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mswin32, x86-mingw32, x64-mingw32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mswin32 x86-mingw32 x64-mingw32`.
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
You have requested:
  puppet = 5.3.2

The bundle currently has puppet locked at 5.3.3.
Try running `bundle update puppet`

If you are updating multiple gems in your Gemfile at once,
try passing them all to `bundle update`


pdk (FATAL): Unable to install missing Gemfile dependencies.
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.1.9/lib/ruby/gems/2.1.0/gems/pdk-1.3.1/lib/pdk/util/bundler.rb:44:in `ensure_bundle!'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.1.9/lib/ruby/gems/2.1.0/gems/pdk-1.3.1/lib/pdk/module/convert.rb:66:in `invoke'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.1.9/lib/ruby/gems/2.1.0/gems/pdk-1.3.1/lib/pdk/cli/convert.rb:22:in `block (2 levels) in <module:CLI>'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.1.9/lib/ruby/gems/2.1.0/gems/cri-2.9.1/lib/cri/command.rb:319:in `call'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.1.9/lib/ruby/gems/2.1.0/gems/cri-2.9.1/lib/cri/command.rb:319:in `run_this'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.1.9/lib/ruby/gems/2.1.0/gems/cri-2.9.1/lib/cri/command.rb:264:in `run'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.1.9/lib/ruby/gems/2.1.0/gems/cri-2.9.1/lib/cri/command.rb:282:in `run'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.1.9/lib/ruby/gems/2.1.0/gems/pdk-1.3.1/lib/pdk/cli.rb:17:in `run'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.1.9/lib/ruby/gems/2.1.0/gems/pdk-1.3.1/exe/pdk:6:in `<top (required)>'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.1.9/bin/pdk:23:in `load'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.1.9/bin/pdk:23:in `<main>'
```

</details>

**Comment by DavidS** [comment]
@jeremy-asher setting `PUPPET_GEM_VERSION` is not "supported" supported. It **should** work during `test unit`, but it won't do anything useful during `convert`. We're planning to implement full support for testing against different puppet versions in https://tickets.puppetlabs.com/browse/PDK-414

**Comment by DavidS** [comment]
On second look, I was not trivially able to reproduce your issue, @jeremy-asher .

**Comment by jeremy-asher** [comment]
@DavidS good to hear that official support is planned.  It would be nice if you can leave "unofficial" support for older releases, but I understand if you need to strip them as part of that work.

I believe my crash above was with the CentOS 6 RPM and the latest version of PDK and the ntp module available at the time I posted it.

**Comment by DavidS** [comment]
1) thanks, I can reproduce it now with https://github.com/puppetlabs/puppetlabs-ntp/commit/d8a1b3afdf33f4d7e90a8ad4836ce77253238ad8

2) setting `PUPPET_GEM_VERSION` will not change the output of `pdk convert`, it will only influence `pdk test unit`. You can leave it out from your conversion, and still get its benefits at test time.

**Comment by DavidS** [comment]
Further analysis showed why I couldn't repro this originally. The error is caused by interacting with the `Gemfile.lock` we install to preselect gems from the cache. This only happens on packaged pdk versions.

I've been able to workaround the issue locally by running `PUPPET_GEM_VERSION=5.1.0 pdk bundle update` before `test unit`.

It is unlikely we'll be able to address this before https://tickets.puppetlabs.com/browse/PDK-414 as it is a fundamental conflict between "by default the pdk should always use its local gems" and "support 'arbitrary' shenanigans in the Gemfile".
