### ISSUE TITLE
Support for deep directory structure in templates

### ISSUE THREAD

**Issue by rtib** [puppetlabs/pdk#445]
I tried to create a template containing `moduleroot_init/spec/nodesets` directory with some nodes definitions for an acceptance test wireframe. The `pdk new module` command ended up with being unable to create directory structures deeper than one level:
```
pdk (DEBUG): Rendering 'spec/nodesets'...
pdk (FATAL): Failed to render template 'spec/nodesets'
ArgumentError: '/var/folders/f2/s1z9f_qd24n417_4w8q8c2fr0000gn/T/pdk-templates20180301-3694-h8fiix/moduleroot_init/spec/nodesets' is not a readable file
pdk (DEBUG): ArgumentError: '/var/folders/f2/s1z9f_qd24n417_4w8q8c2fr0000gn/T/pdk-templates20180301-3694-h8fiix/moduleroot_init/spec/nodesets' is not a readable file
pdk (DEBUG): /opt/local/lib/ruby2.4/gems/2.4.0/gems/pdk-1.4.1/lib/pdk/template_file.rb:62:in `template_content'
pdk (DEBUG): /opt/local/lib/ruby2.4/gems/2.4.0/gems/pdk-1.4.1/lib/pdk/template_file.rb:86:in `render_plain'
pdk (DEBUG): /opt/local/lib/ruby2.4/gems/2.4.0/gems/pdk-1.4.1/lib/pdk/template_file.rb:43:in `render'
pdk (DEBUG): /opt/local/lib/ruby2.4/gems/2.4.0/gems/pdk-1.4.1/lib/pdk/module/templatedir.rb:131:in `block in render'
pdk (DEBUG): /opt/local/lib/ruby2.4/gems/2.4.0/gems/pdk-1.4.1/lib/pdk/module/templatedir.rb:126:in `each'
pdk (DEBUG): /opt/local/lib/ruby2.4/gems/2.4.0/gems/pdk-1.4.1/lib/pdk/module/templatedir.rb:126:in `render'
pdk (DEBUG): /opt/local/lib/ruby2.4/gems/2.4.0/gems/pdk-1.4.1/lib/pdk/generate/module.rb:58:in `block in invoke'
pdk (DEBUG): /opt/local/lib/ruby2.4/gems/2.4.0/gems/pdk-1.4.1/lib/pdk/module/templatedir.rb:82:in `initialize'
pdk (DEBUG): /opt/local/lib/ruby2.4/gems/2.4.0/gems/pdk-1.4.1/lib/pdk/generate/module.rb:57:in `new'
pdk (DEBUG): /opt/local/lib/ruby2.4/gems/2.4.0/gems/pdk-1.4.1/lib/pdk/generate/module.rb:57:in `invoke'
pdk (DEBUG): /opt/local/lib/ruby2.4/gems/2.4.0/gems/pdk-1.4.1/lib/pdk/cli/new/module.rb:37:in `block (2 levels) in <module:CLI>'
pdk (DEBUG): /opt/local/lib/ruby2.4/gems/2.4.0/gems/cri-2.9.1/lib/cri/command.rb:319:in `run_this'
pdk (DEBUG): /opt/local/lib/ruby2.4/gems/2.4.0/gems/cri-2.9.1/lib/cri/command.rb:264:in `run'
pdk (DEBUG): /opt/local/lib/ruby2.4/gems/2.4.0/gems/cri-2.9.1/lib/cri/command.rb:282:in `run'
pdk (DEBUG): /opt/local/lib/ruby2.4/gems/2.4.0/gems/cri-2.9.1/lib/cri/command.rb:282:in `run'
pdk (DEBUG): /opt/local/lib/ruby2.4/gems/2.4.0/gems/pdk-1.4.1/lib/pdk/cli.rb:17:in `run'
pdk (DEBUG): /opt/local/lib/ruby2.4/gems/2.4.0/gems/pdk-1.4.1/exe/pdk:6:in `<top (required)>'
pdk (DEBUG): /opt/local/bin/pdk:23:in `load'
pdk (DEBUG): /opt/local/bin/pdk:23:in `<main>'
```

Having a look on `template_file.rb`, it seems not to consider a directory as a valid type directory entry, and it doesn't recurse to in-depth rendering template directory structure.

**Comment by bmjen** [comment]
Thanks @rtib ! This looks like a bug in the module renderer, it should be able to render files in nested directories: https://tickets.puppetlabs.com/browse/PDK-906 was created to track this issue.

**Comment by nabertrand** [comment]
My team is unable to use nested directories in our templates until this is resolved. Could we try and get this into the next release? It looks like there are three potential fixes submitted now :smiley: (#512, #524, #540). Thanks!
