### ISSUE TITLE
Checking Ruby code style fails

### ISSUE THREAD

**Issue by Tamerz** [puppetlabs/pdk#697]
**Describe the bug**
When running `pdk validate`, the "Checking Ruby code style" step always shows a failure, even right after creating a new module and changing nothing else.

**To Reproduce**
Create a new module and run `pdk validate`:

```bash
$ pdk new module thetest
$ cd thetest
$ pdk validate
pdk (INFO): Running all available validators...
pdk (INFO): Using Ruby 2.5.3
pdk (INFO): Using Puppet 6.5.0
[✔] Checking metadata syntax (metadata.json tasks/*.json).
[✔] Checking module metadata style (metadata.json).
[✔] Checking YAML syntax (["**/*.yaml", "*.yaml", "**/*.yml", "*.yml"]).
[✖] Checking Ruby code style (**/**.rb).
[✔] Checking task names (tasks/**/*).
info: puppet-syntax: ./: Target does not contain any files to validate (**/*.pp).
info: puppet-lint: ./: Target does not contain any files to validate (**/*.pp).
info: task-metadata-lint: ./: Target does not contain any files to validate (tasks/*.json).
```

Running with debug shows where the validation is failing:

```
$ pdk validate --debug
pdk (DEBUG): Execution of '/private/tmp/thetest/bin/rubocop --format json' complete (duration: 1.693949s; exit code: 1)
pdk (DEBUG): STDOUT: N/A
pdk (DEBUG): STDERR: 
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rubocop-i18n-1.2.0/lib/rubocop-i18n.rb:1:in `require': cannot load such file -- rubocop/cop/i18n (LoadError)
	from /opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rubocop-i18n-1.2.0/lib/rubocop-i18n.rb:1:in `<top (required)>'
	from /opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rubocop-0.49.1/lib/rubocop/config_loader_resolver.rb:15:in `require'
	from /opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rubocop-0.49.1/lib/rubocop/config_loader_resolver.rb:15:in `block in resolve_requires'
	from /opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rubocop-0.49.1/lib/rubocop/config_loader_resolver.rb:11:in `each'
	from /opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rubocop-0.49.1/lib/rubocop/config_loader_resolver.rb:11:in `resolve_requires'
	from /opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rubocop-0.49.1/lib/rubocop/config_loader.rb:37:in `load_file'
	from /opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rubocop-0.49.1/lib/rubocop/config_loader.rb:113:in `configuration_from_file'
	from /opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rubocop-0.49.1/lib/rubocop/config_store.rb:44:in `for'
	from /opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rubocop-0.49.1/lib/rubocop/target_finder.rb:161:in `excluded_dirs'
	from /opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rubocop-0.49.1/lib/rubocop/target_finder.rb:139:in `find_files'
	from /opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rubocop-0.49.1/lib/rubocop/target_finder.rb:112:in `target_files_in_dir'
	from /opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rubocop-0.49.1/lib/rubocop/target_finder.rb:83:in `find'
	from /opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:58:in `find_target_files'
	from /opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:34:in `run'
	from /opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rubocop-0.49.1/lib/rubocop/cli.rb:82:in `execute_runner'
	from /opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rubocop-0.49.1/lib/rubocop/cli.rb:28:in `run'
	from /opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rubocop-0.49.1/bin/rubocop:13:in `block in <top (required)>'
	from /opt/puppetlabs/pdk/private/ruby/2.5.3/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
	from /opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rubocop-0.49.1/bin/rubocop:12:in `<top (required)>'
	from /private/tmp/thetest/bin/rubocop:29:in `load'
	from /private/tmp/thetest/bin/rubocop:29:in `<main>'
```

**Expected behavior**
It should pass successfully with a check mark and not an x.

**Additional context**
This is with PDK version 1.11.0 on MacOS 10.13.6 installed via homebrew.

**Comment by Tamerz** [comment]
I noticed that if I run `pdk validate` against a module made with PDK version 1.7.0 it works fine.

**Comment by scotje** [comment]
My preliminary troubleshooting suggests this might be a permissions issue in the macOS (at least 10.13) packages.

@Tamerz can you post the output of `ls -la /opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rubocop-i18n-1.2.0/lib/rubocop/cop/`?

**Comment by Tamerz** [comment]
> My preliminary troubleshooting suggests this might be a permissions issue in the macOS (at least 10.13) packages.
> 
> @Tamerz can you post the output of `ls -la /opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rubocop-i18n-1.2.0/lib/rubocop/cop/`?

@scotje Sure thing.
```
total 8
drwxr-xr-x  4 root  wheel  128 Jun 27 09:34 .
drwxr-xr-x  4 root  wheel  128 Jun 27 09:34 ..
drwxr-xr-x  4 root  wheel  128 Jun 27 09:34 i18n
-rw-rw----  1 root  wheel  323 Jun 27 09:34 i18n.rb
```

**Comment by Tamerz** [comment]
PDK 1.11.1 was released. I upgraded and still have the same issue.

**Comment by robbyt** [comment]
As a workaround, `find /opt/puppetlabs -name i18n -type d -exec sudo chmod -R 755 {} \;`

**Comment by robbyt** [comment]
Also, after applying that above workaround for fix the permissions, rubocop only works on PDK's Ruby 2.5.3:

```
$ PDK_PUPPET_VERSION=4 pdk bundle exec rake rubocop
pdk (INFO): Using Ruby 2.1.9
pdk (INFO): Using Puppet 4.10.12
Running RuboCop...
rake aborted!
LoadError: cannot load such file -- rubocop/cop/i18n
/opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/rubocop-i18n-1.2.0/lib/rubocop-i18n.rb:1:in `require'
/opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/rubocop-i18n-1.2.0/lib/rubocop-i18n.rb:1:in `<top (required)>'
/opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/rubocop-0.49.1/lib/rubocop/config_loader_resolver.rb:15:in `require'
/opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/rubocop-0.49.1/lib/rubocop/config_loader_resolver.rb:15:in `block in resolve_requires'
/opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/rubocop-0.49.1/lib/rubocop/config_loader_resolver.rb:11:in `each'
/opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/rubocop-0.49.1/lib/rubocop/config_loader_resolver.rb:11:in `resolve_requires'
/opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/rubocop-0.49.1/lib/rubocop/config_loader.rb:37:in `load_file'
/opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/rubocop-0.49.1/lib/rubocop/config_loader.rb:113:in `configuration_from_file'
/opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/rubocop-0.49.1/lib/rubocop/config_store.rb:44:in `for'
/opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/rubocop-0.49.1/lib/rubocop/cli.rb:103:in `apply_default_formatter'
/opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/rubocop-0.49.1/lib/rubocop/cli.rb:26:in `run'
/opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/rubocop-0.49.1/lib/rubocop/rake_task.rb:48:in `run_cli'
/opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/rubocop-0.49.1/lib/rubocop/rake_task.rb:36:in `run_main_task'
/opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/rubocop-0.49.1/lib/rubocop/rake_task.rb:28:in `block (2 levels) in initialize'
/opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/rubocop-0.49.1/lib/rubocop/rake_task.rb:26:in `block in initialize'
/opt/puppetlabs/pdk/share/cache/ruby/2.1.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/opt/puppetlabs/pdk/private/ruby/2.1.9/bin/bundle:23:in `load'
/opt/puppetlabs/pdk/private/ruby/2.1.9/bin/bundle:23:in `<main>'
Tasks: TOP => rubocop
(See full trace by running task with --trace)
```

```
$ PDK_PUPPET_VERSION=5 pdk bundle exec rake rubocop
pdk (INFO): Using Ruby 2.4.5
pdk (INFO): Using Puppet 5.5.14
Running RuboCop...
rake aborted!
LoadError: cannot load such file -- rubocop/cop/i18n
/opt/puppetlabs/pdk/share/cache/ruby/2.4.0/gems/rubocop-i18n-1.2.0/lib/rubocop-i18n.rb:1:in `require'
/opt/puppetlabs/pdk/share/cache/ruby/2.4.0/gems/rubocop-i18n-1.2.0/lib/rubocop-i18n.rb:1:in `<top (required)>'
/opt/puppetlabs/pdk/share/cache/ruby/2.4.0/gems/rubocop-0.49.1/lib/rubocop/config_loader_resolver.rb:15:in `require'
/opt/puppetlabs/pdk/share/cache/ruby/2.4.0/gems/rubocop-0.49.1/lib/rubocop/config_loader_resolver.rb:15:in `block in resolve_requires'
/opt/puppetlabs/pdk/share/cache/ruby/2.4.0/gems/rubocop-0.49.1/lib/rubocop/config_loader_resolver.rb:11:in `each'
/opt/puppetlabs/pdk/share/cache/ruby/2.4.0/gems/rubocop-0.49.1/lib/rubocop/config_loader_resolver.rb:11:in `resolve_requires'
/opt/puppetlabs/pdk/share/cache/ruby/2.4.0/gems/rubocop-0.49.1/lib/rubocop/config_loader.rb:37:in `load_file'
/opt/puppetlabs/pdk/share/cache/ruby/2.4.0/gems/rubocop-0.49.1/lib/rubocop/config_loader.rb:113:in `configuration_from_file'
/opt/puppetlabs/pdk/share/cache/ruby/2.4.0/gems/rubocop-0.49.1/lib/rubocop/config_store.rb:44:in `for'
/opt/puppetlabs/pdk/share/cache/ruby/2.4.0/gems/rubocop-0.49.1/lib/rubocop/cli.rb:103:in `apply_default_formatter'
/opt/puppetlabs/pdk/share/cache/ruby/2.4.0/gems/rubocop-0.49.1/lib/rubocop/cli.rb:26:in `run'
/opt/puppetlabs/pdk/share/cache/ruby/2.4.0/gems/rubocop-0.49.1/lib/rubocop/rake_task.rb:48:in `run_cli'
/opt/puppetlabs/pdk/share/cache/ruby/2.4.0/gems/rubocop-0.49.1/lib/rubocop/rake_task.rb:36:in `run_main_task'
/opt/puppetlabs/pdk/share/cache/ruby/2.4.0/gems/rubocop-0.49.1/lib/rubocop/rake_task.rb:28:in `block (2 levels) in initialize'
/opt/puppetlabs/pdk/share/cache/ruby/2.4.0/gems/rubocop-0.49.1/lib/rubocop/rake_task.rb:26:in `block in initialize'
/opt/puppetlabs/pdk/share/cache/ruby/2.4.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/opt/puppetlabs/pdk/private/ruby/2.4.5/bin/bundle:23:in `load'
/opt/puppetlabs/pdk/private/ruby/2.4.5/bin/bundle:23:in `<main>'
Tasks: TOP => rubocop
(See full trace by running task with --trace)
```

```
$ PDK_PUPPET_VERSION=6 pdk bundle exec rake rubocop
pdk (INFO): Using Ruby 2.5.3
pdk (INFO): Using Puppet 6.5.0
Running RuboCop...
Inspecting 4 files
....

4 files inspected, no offenses detected
```

**Comment by natemccurdy** [comment]
The `i18n.rb` and the `gettext.rb` files as well as the Ruby files in the `gettext/` folder all are not readable by my user account.

Here are the specific `chmod` operations that fixed the issue for me:
```
sudo chmod 664 /opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rubocop-i18n-1.2.0/lib/rubocop/cop/i18n.rb

sudo chmod 664 /opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rubocop-i18n-1.2.0/lib/rubocop/cop/i18n/gettext.rb

sudo chmod 664 /opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rubocop-i18n-1.2.0/lib/rubocop/cop/i18n/gettext/*.rb
```

```
$ pdk validate                                                 
pdk (INFO): Running all available validators...
pdk (INFO): Using Ruby 2.5.3
pdk (INFO): Using Puppet 6.5.0
[✔] Checking metadata syntax (metadata.json tasks/*.json).
[✔] Checking module metadata style (metadata.json).
[✔] Checking YAML syntax (["**/*.yaml", "*.yaml", "**/*.yml", "*.yml"]).
[✔] Checking Puppet manifest syntax (**/*.pp).
[✔] Checking Puppet manifest style (**/*.pp).
[✔] Checking Ruby code style (**/**.rb).
info: task-name: ./: Target does not contain any files to validate (tasks/**/*).
info: task-metadata-lint: ./: Target does not contain any files to validate (tasks/*.json).

$ pdk --version
1.11.1
```

**Comment by scotje** [comment]
Hello all, this appears to be an issue with how the `rubocop-i18n` gem is being packaged. I'm adding a workaround/fix to the PDK packaging pipelines and have also filed the above issue with the `rubocop-i18n` maintainers. I'm not sure why this issue only seems to manifest on macOS right now, but possibly the other platform package managers are correcting the permissions at install-time.

**Comment by scotje** [comment]
Workaround in PDK packaging config added https://github.com/puppetlabs/pdk-vanagon/pull/216

This should be included in the next release of PDK.

**Comment by reenberg** [comment]
I can confirm that I had the same issue on a CentOs 7 system, trying to upgrade from PDK 1.11.1 to 1.12.0.  Quite a few files inside the `rubocop-i18n-1.2.0` was missing read permissions by others.  I believe they were just `-rw-r-----`.  It was both the `i18n.rb` file and also all the files under the `i18n/gettext/` folder.  Adding the read permission for others helped the issue.

**Comment by scotje** [comment]
@reenberg Are you saying that upgrading from 1.11.0 to 1.12.0 did not resolve this and you had to manually adjust the permissions? I wonder if RPM doesn't compare permissions of files that already exist on disk when upgrading a package?

**Comment by reenberg** [comment]
Sorry for the late reply (was off on vacation).

I have originally installed PDK from the puppetlabs repository on my CentOs 7 machine.  I do believe that I then installed the newer version of PDK as a gem, and thus got the newest version automatically.  So I would argue it corresponds to having installed PDK 1.12.0 from scratch.

Note that I installed the gem using the embedded ruby environment that puppet comes with, as CentOs 7 natively only have Ruby 2.0 and i believe there were some dependency issues that required Ruby >= 2.3.  So the gem got installed within the /opt/puppetlabs/puppet/xxx path.  I just added the bin folder within there to my path, and then I had to fix the file permissions.

So no RPM was involved with the 1.12.0 issues.

**Comment by scotje** [comment]
OK, yeah if you install from a gem as root (or some other user other than the user you then try to run PDK as) you may still run into this issue. Until https://github.com/puppetlabs/rubocop-i18n/issues/33 is resolved and a new version of the gem is released. Unfortunately I don't know of a way for us to fix this on the PDK-side for a gem-based installation.

**Comment by scotje** [comment]
There is a new release of the rubocop-i18n gem now that hopefully fixes this.
