### ISSUE TITLE
Problem running "pdk validate manifests/" with pdk 1.12.0

### ISSUE THREAD

**Issue by reenberg** [puppetlabs/pdk#722]
**Describe the bug**
When running `pdk validate` and specifying a folder as one of the targets, then you get a type error: 
```
[|] Checking metadata syntax (metadata.json tasks/*.json)./opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.12.0/lib/pdk/validate/metadata/metadata_syntax.rb:63:in `readable?': no implicit conversion of nil into String (TypeError)
```
The issue is that `base_validator.rb#parse_targets` returns a list containing `nil` (`[nil]`), when you supply a directory as a target, which doesn't match the validators list of patterns. 

This is due to the `map` function being used on [line 55](https://github.com/puppetlabs/pdk/blob/master/lib/pdk/validate/base_validator.rb#L55).  So either the `target_list` variable should be "compacted", or the `map` should be changed to a `select` or `reject`.  

I haven't created a PR for this as I don't know how you would prefer the debug statement being handled in the case of a select/reject (the code get rather ugly with if statements returning true/false), or if you would just prefer the map with a compact at the end.

I'm not sure if this relates to #570 at all.

**To Reproduce**
Run the following command, potentially substituting manifests/ with any folder you have in your module directory. 

```
# pdk validate manifests/
pdk (INFO): Running all available validators...
pdk (INFO): Using Ruby 2.5.3
pdk (INFO): Using Puppet 6.7.2
[|] Checking metadata syntax (metadata.json tasks/*.json)./opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.12.0/lib/pdk/validate/metadata/metadata_syntax.rb:63:in `readable?': no implicit conversion of nil into String (TypeError)
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.12.0/lib/pdk/validate/metadata/metadata_syntax.rb:63:in `block in invoke'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.12.0/lib/pdk/validate/metadata/metadata_syntax.rb:62:in `each'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.12.0/lib/pdk/validate/metadata/metadata_syntax.rb:62:in `invoke'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.12.0/lib/pdk/validate/metadata_validator.rb:22:in `block in invoke'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.12.0/lib/pdk/validate/metadata_validator.rb:21:in `each'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.12.0/lib/pdk/validate/metadata_validator.rb:21:in `invoke'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.12.0/lib/pdk/cli/validate.rb:119:in `block (3 levels) in <module:CLI>'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.12.0/lib/pdk/cli/validate.rb:118:in `each'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.12.0/lib/pdk/cli/validate.rb:118:in `block (2 levels) in <module:CLI>'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:329:in `run_this'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:269:in `run'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:287:in `run'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.12.0/lib/pdk/cli.rb:55:in `run'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.12.0/exe/pdk:6:in `<top (required)>'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/bin/pdk:23:in `load'
        from /opt/puppetlabs/pdk/private/ruby/2.4.5/bin/pdk:23:in `<main>'
```

```
pdk (INFO): Running all available validators...
pdk (DEBUG): Submitting analytics: {
  "v": 1,
  "cid": "5446ce5b-a8c1-4772-943a-9979a3f0ef1b",
  "tid": "UA-139917834-1",
  "an": "pdk",
  "av": "1.12.0",
  "aiid": "package",
  "aip": true,
  "ul": "en-US",
  "cd1": "Debian 10",
  "t": "screenview",
  "cd": "validate",
  "cd3": "2.4.5",
  "cd2": "default",
  "cd4": "debug=true"
}
pdk (INFO): Using Ruby 2.5.3
pdk (INFO): Using Puppet 6.7.2
pdk (DEBUG): Checking for missing Gemfile dependencies.
pdk (DEBUG): Using '/opt/puppetlabs/pdk/private/ruby/2.5.3/bin/bundle' from PDK package.
pdk (DEBUG): Executing '/opt/puppetlabs/pdk/private/ruby/2.5.3/bin/bundle check --gemfile=/tmp/y/Gemfile --dry-run'
pdk (DEBUG): Command environment:
pdk (DEBUG):   TERM: screen-256color
pdk (DEBUG):   PUPPET_GEM_VERSION: 6.7.2
pdk (DEBUG):   FACTER_GEM_VERSION: 
pdk (DEBUG):   HIERA_GEM_VERSION: 
pdk (DEBUG):   BUNDLE_IGNORE_CONFIG: 1
pdk (DEBUG):   GEM_HOME: /root/.pdk/cache/ruby/2.5.0
pdk (DEBUG):   GEM_PATH: /opt/puppetlabs/pdk/private/ruby/2.5.3/lib/ruby/gems/2.5.0:/opt/puppetlabs/pdk/share/cache/ruby/2.5.0:/opt/puppetlabs/pdk/private/puppet/ruby/2.5.0
pdk (DEBUG):   PATH: /opt/puppetlabs/pdk/private/ruby/2.5.3/bin:/root/.pdk/cache/ruby/2.5.0/bin:/opt/puppetlabs/pdk/private/ruby/2.5.3/lib/ruby/gems/2.5.0/bin:/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/bin:/opt/puppetlabs/pdk/private/puppet/ruby/2.5.0/bin:/opt/puppetlabs/pdk/bin:/opt/puppetlabs/pdk/private/git/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
pdk (DEBUG): Execution of '/opt/puppetlabs/pdk/private/ruby/2.5.3/bin/bundle check --gemfile=/tmp/y/Gemfile --dry-run' complete (duration: 0.31545237s; exit code: 0)
pdk (DEBUG): STDOUT: 
Resolving dependencies...
The dependency rb-readline (= 0.5.5) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mswin32, x86-mingw32, x64-mingw32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mswin32 x86-mingw32 x64-mingw32`.
The dependency puppet-module-win-default-r2.5 (~> 0.3) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mswin32, x86-mingw32, x64-mingw32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mswin32 x86-mingw32 x64-mingw32`.
The dependency puppet-module-win-dev-r2.5 (~> 0.3) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mswin32, x86-mingw32, x64-mingw32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mswin32 x86-mingw32 x64-mingw32`.
The Gemfile's dependencies are satisfied

pdk (DEBUG): STDERR: N/A
pdk (DEBUG): Updating Gemfile dependencies.
pdk (DEBUG): Using '/opt/puppetlabs/pdk/private/ruby/2.5.3/bin/bundle' from PDK package.
pdk (DEBUG): Executing '/opt/puppetlabs/pdk/private/ruby/2.5.3/bin/bundle lock --lockfile=/tmp/y/Gemfile.lock --update --local'
pdk (DEBUG): Command environment:
pdk (DEBUG):   TERM: screen-256color
pdk (DEBUG):   PUPPET_GEM_VERSION: 6.7.2
pdk (DEBUG):   FACTER_GEM_VERSION: 
pdk (DEBUG):   HIERA_GEM_VERSION: 
pdk (DEBUG):   BUNDLE_GEMFILE: /tmp/y/Gemfile
pdk (DEBUG):   BUNDLE_IGNORE_CONFIG: 1
pdk (DEBUG):   GEM_HOME: /root/.pdk/cache/ruby/2.5.0
pdk (DEBUG):   GEM_PATH: /opt/puppetlabs/pdk/private/ruby/2.5.3/lib/ruby/gems/2.5.0:/opt/puppetlabs/pdk/share/cache/ruby/2.5.0:/opt/puppetlabs/pdk/private/puppet/ruby/2.5.0
pdk (DEBUG):   PATH: /opt/puppetlabs/pdk/private/ruby/2.5.3/bin:/root/.pdk/cache/ruby/2.5.0/bin:/opt/puppetlabs/pdk/private/ruby/2.5.3/lib/ruby/gems/2.5.0/bin:/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/bin:/opt/puppetlabs/pdk/private/puppet/ruby/2.5.0/bin:/opt/puppetlabs/pdk/bin:/opt/puppetlabs/pdk/private/git/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
pdk (DEBUG): Completed analytics submission
pdk (DEBUG): Execution of '/opt/puppetlabs/pdk/private/ruby/2.5.3/bin/bundle lock --lockfile=/tmp/y/Gemfile.lock --update --local' complete (duration: 0.412577917s; exit code: 0)
pdk (DEBUG): STDOUT: 
Writing lockfile to /tmp/y/Gemfile.lock
Resolving dependencies...
The dependency rb-readline (= 0.5.5) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mswin32, x86-mingw32, x64-mingw32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mswin32 x86-mingw32 x64-mingw32`.
The dependency puppet-module-win-default-r2.5 (~> 0.3) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mswin32, x86-mingw32, x64-mingw32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mswin32 x86-mingw32 x64-mingw32`.
The dependency puppet-module-win-dev-r2.5 (~> 0.3) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mswin32, x86-mingw32, x64-mingw32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mswin32 x86-mingw32 x64-mingw32`.

pdk (DEBUG): STDERR: N/A
pdk (DEBUG): Checking for missing Gemfile dependencies.
pdk (DEBUG): Using '/opt/puppetlabs/pdk/private/ruby/2.5.3/bin/bundle' from PDK package.
pdk (DEBUG): Executing '/opt/puppetlabs/pdk/private/ruby/2.5.3/bin/bundle check --gemfile=/tmp/y/Gemfile --dry-run'
pdk (DEBUG): Command environment:
pdk (DEBUG):   TERM: screen-256color
pdk (DEBUG):   PUPPET_GEM_VERSION: 
pdk (DEBUG):   FACTER_GEM_VERSION: 
pdk (DEBUG):   HIERA_GEM_VERSION: 
pdk (DEBUG):   BUNDLE_IGNORE_CONFIG: 1
pdk (DEBUG):   GEM_HOME: /root/.pdk/cache/ruby/2.5.0
pdk (DEBUG):   GEM_PATH: /opt/puppetlabs/pdk/private/ruby/2.5.3/lib/ruby/gems/2.5.0:/opt/puppetlabs/pdk/share/cache/ruby/2.5.0:/opt/puppetlabs/pdk/private/puppet/ruby/2.5.0
pdk (DEBUG):   PATH: /opt/puppetlabs/pdk/private/ruby/2.5.3/bin:/root/.pdk/cache/ruby/2.5.0/bin:/opt/puppetlabs/pdk/private/ruby/2.5.3/lib/ruby/gems/2.5.0/bin:/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/bin:/opt/puppetlabs/pdk/private/puppet/ruby/2.5.0/bin:/opt/puppetlabs/pdk/bin:/opt/puppetlabs/pdk/private/git/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
pdk (DEBUG): Execution of '/opt/puppetlabs/pdk/private/ruby/2.5.3/bin/bundle check --gemfile=/tmp/y/Gemfile --dry-run' complete (duration: 0.28994872s; exit code: 0)
pdk (DEBUG): STDOUT: 
Resolving dependencies...
The dependency rb-readline (= 0.5.5) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mswin32, x86-mingw32, x64-mingw32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mswin32 x86-mingw32 x64-mingw32`.
The dependency puppet-module-win-default-r2.5 (~> 0.3) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mswin32, x86-mingw32, x64-mingw32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mswin32 x86-mingw32 x64-mingw32`.
The dependency puppet-module-win-dev-r2.5 (~> 0.3) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mswin32, x86-mingw32, x64-mingw32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mswin32 x86-mingw32 x64-mingw32`.
The Gemfile's dependencies are satisfied

pdk (DEBUG): STDERR: N/A
pdk (DEBUG): metadata-syntax: Skipped 'manifests/'. Target directory does not exist.
/opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.12.0/lib/pdk/validate/metadata/metadata_syntax.rb:63:in `readable?': no implicit conversion of nil into String (TypeError)
	from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.12.0/lib/pdk/validate/metadata/metadata_syntax.rb:63:in `block in invoke'
	from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.12.0/lib/pdk/validate/metadata/metadata_syntax.rb:62:in `each'
	from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.12.0/lib/pdk/validate/metadata/metadata_syntax.rb:62:in `invoke'
	from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.12.0/lib/pdk/validate/metadata_validator.rb:22:in `block in invoke'
	from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.12.0/lib/pdk/validate/metadata_validator.rb:21:in `each'
	from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.12.0/lib/pdk/validate/metadata_validator.rb:21:in `invoke'
	from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.12.0/lib/pdk/cli/validate.rb:119:in `block (3 levels) in <module:CLI>'
	from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.12.0/lib/pdk/cli/validate.rb:118:in `each'
	from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.12.0/lib/pdk/cli/validate.rb:118:in `block (2 levels) in <module:CLI>'
	from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:329:in `run_this'
	from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:269:in `run'
	from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:287:in `run'
	from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.12.0/lib/pdk/cli.rb:55:in `run'
	from /opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0/gems/pdk-1.12.0/exe/pdk:6:in `<top (required)>'
	from /opt/puppetlabs/pdk/private/ruby/2.4.5/bin/pdk:23:in `load'
	from /opt/puppetlabs/pdk/private/ruby/2.4.5/bin/pdk:23:in `<main>'
```

**Expected behavior**
The output from all the validators, concentrated to the specified targets (files and directories).

**Additional context**
- PDK was installed on a Debian 10/Buster system using apt, following the official guide: https://puppet.com/docs/pdk/1.x/pdk_install.html
- pdk version: 1.12.0
- This was also tested on CentOs 7.

**Comment by glennsarti** [comment]
Repro'd on Windows as well.

`bin\pdk validate manifests`

**Comment by glennsarti** [comment]
`bin\pdk validate manifests/*` works
