### ISSUE TITLE
rake build gives error NoMethodError: undefined method `package_install?' for PDK::Util:Module

### ISSUE THREAD

**Issue by hajee** [puppetlabs/pdk#770]
`rake build:pdk` causes undefined method error.

**To Reproduce**

```
$ rake build::pdk

NoMethodError: undefined method `package_install?' for PDK::Util:Module
/source/vendor/ruby/2.5.0/gems/pdk-1.14.0/lib/pdk/module/metadata.rb:112:in `from_file'
/source/vendor/ruby/2.5.0/gems/pdk-1.14.0/lib/pdk/module/build.rb:23:in `metadata'
/source/vendor/ruby/2.5.0/gems/pdk-1.14.0/lib/pdk/module/build.rb:90:in `release_name'
/source/vendor/ruby/2.5.0/gems/pdk-1.14.0/lib/pdk/module/build.rb:60:in `build_dir'
/source/vendor/ruby/2.5.0/gems/pdk-1.14.0/lib/pdk/module/build.rb:81:in `cleanup_build_dir'
/source/vendor/ruby/2.5.0/gems/pdk-1.14.0/lib/pdk/module/build.rb:42:in `ensure in build'
/source/vendor/ruby/2.5.0/gems/pdk-1.14.0/lib/pdk/module/build.rb:42:in `build'
/source/vendor/ruby/2.5.0/gems/pdk-1.14.0/lib/pdk/module/build.rb:5:in `invoke'
/source/vendor/ruby/2.5.0/gems/puppetlabs_spec_helper-2.14.1/lib/puppetlabs_spec_helper/rake_tasks.rb:147:in `block (2 levels) in <top (required)>'
/source/vendor/ruby/2.5.0/gems/puppetlabs_spec_helper-2.14.1/lib/puppetlabs_spec_helper/rake_tasks.rb:129:in `block in <top (required)>'
/source/vendor/ruby/2.5.0/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/bin/bundle:22:in `<main>'
```
The task is defined in `/puppetlabs_spec_helper-2.14.1/lib/puppetlabs_spec_helper/rake_tasks.rb:143`

**Expected behavior**

It should build the pkg for the module

**Additional context**

Error is caused because of lacking require in `metadata.rb`. It is not caught by rspec tests because it the meethod is stubbed there.

**Comment by scotje** [comment]
Hi @hajee, thanks for the bug report and the PR to fix it! We will get the fix merged and hopefully get a `1.14.1` release out soon with the fix.
