### ISSUE TITLE
Unable to automatically generate the changelog

### ISSUE THREAD

**Issue by mrolli** [puppetlabs/pdk#855]
**Describe the bug**
When doing the automatic changelog generation during a release prep the execution fails with the following trace. It seems that Bundle does not have the rubygems method. 

````
pdk (INFO): Releasing unibehpc/testmodule - from version 0.1.0
/opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/pdk-1.16.0/lib/pdk/util/changelog_generator.rb:12:in `github_changelog_generator_available!': undefined method `rubygems' for PDK::Util::Bundler:Module (NoMethodError)
        from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/pdk-1.16.0/lib/pdk/util/changelog_generator.rb:19:in `generate_changelog'
        from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/pdk-1.16.0/lib/pdk/module/release.rb:48:in `run'
        from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/pdk-1.16.0/lib/pdk/cli/release/prep.rb:36:in `block (2 levels) in <module:CLI>'
        from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:329:in `run_this'
        from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:269:in `run'
        from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:287:in `run'
        from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:287:in `run'
        from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/pdk-1.16.0/lib/pdk/cli.rb:68:in `run'
        from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/pdk-1.16.0/exe/pdk:6:in `<top (required)>'
        from /opt/puppetlabs/pdk/private/ruby/2.4.9/bin/pdk:23:in `load'
        from /opt/puppetlabs/pdk/private/ruby/2.4.9/bin/pdk:23:in `<main>'
````

**To Reproduce**
Run `pdk release prep` and skip all but "automatic changelog generation"

**Expected behavior**
A generated CHANGELOG.md absed on the commits.

**Additional context**
- PDK package installed using Homebrew
- PDK-1.16.0
- macOS Catalina 10.15.3
- Stock Ruby --> no rvm, rbenv or the like installed
  - ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
  - Bundler version 1.17.2

**Comment by scotje** [comment]
Thanks for the report! It looks like we just need to tweak some of our changelog_generator wrapper code. We'll try to have this fixed up in the next release.
