### ISSUE TITLE
GemNotFound error for public_suffix-3.1.1 when using --add-tests

### ISSUE THREAD

**Issue by kreeuwijk** [puppetlabs/pdk#869]
**Describe the bug**
In a clean PDK install, which has not run `pdk test unit` yet, I tried to add spec test to an existing module. I ran `pdk convert --add-tests` but got an error message:

```
[✖] Examining module contents
/opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/pdk-1.17.0/lib/pdk/util/puppet_strings.rb:42:in `generate_hash': /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:91:in `block in materialize': Could not find public_suffix-3.1.1 in any of the sources (Bundler::GemNotFound) (PDK::Util::PuppetStrings::RunError)
	from /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:85:in `map!'
	from /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:85:in `materialize'
	from /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:170:in `specs'
	from /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:237:in `specs_for'
	from /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:226:in `requested_specs'
	from /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:108:in `block in definition_method'
	from /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:20:in `setup'
	from /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/bundler.rb:107:in `setup'
	from /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/bundler/setup.rb:20:in `<top (required)>'
	from /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/kevin.reeuwijk/code/vmtools_win/bin/puppet:15:in `<main>'
	from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/pdk-1.17.0/lib/pdk/util/puppet_strings.rb:98:in `all_objects'
	from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/pdk-1.17.0/lib/pdk/module/convert.rb:98:in `test_generators'
	from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/pdk-1.17.0/lib/pdk/module/convert.rb:91:in `missing_tests?'
	from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/pdk-1.17.0/lib/pdk/module/convert.rb:87:in `adding_tests?'
	from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/pdk-1.17.0/lib/pdk/module/convert.rb:69:in `run'
	from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/pdk-1.17.0/lib/pdk/module/convert.rb:7:in `invoke'
	from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/pdk-1.17.0/lib/pdk/cli/convert.rb:51:in `block (2 levels) in <module:CLI>'
	from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:329:in `run_this'
	from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:269:in `run'
	from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:287:in `run'
	from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/pdk-1.17.0/lib/pdk/cli.rb:68:in `run'
	from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/pdk-1.17.0/exe/pdk:6:in `<top (required)>'
	from /opt/puppetlabs/pdk/private/ruby/2.4.9/bin/pdk:23:in `load'
	from /opt/puppetlabs/pdk/private/ruby/2.4.9/bin/pdk:23:in `<main>'
```

This error didn't show up later anymore, after `pdk test unit` had run.

**Additional context**
- PDK installation method: homebrew
- PDK version: 1.17.0
- Operating system / platform: MacOS Catalina

**Comment by rodjek** [comment]
Hi @kreeuwijk,

I tried to reproduce this on a clean 10.15 VM with PDK 1.17.0 and it worked fine. Did you have a Gemfile.lock in the module prior to running the convert from a manually managed Ruby environment or previous PDK install?

**Comment by kreeuwijk** [comment]
@rodjek I couldn't reproduce it with a tarball of the previous version of the module either. I believe there was already a Gemfile.lock in the module, but I don't have the history for that file as it is in `.gitignore`... The module was converted with the PDK in 2017, and updated to PDK 1.5, 1.6 and 1.8 since.

**Comment by scotje** [comment]
@rodjek I'm wondering if we need to re-resolve dependencies with bundler earlier in the `pdk convert` process?

**Comment by rodjek** [comment]
I'm pretty sure the problem lies in that we guard running `bundle install` to only happen if `Gemfile` changes during the convert. Unfortunately this doesn't contain a full list of dependencies like `Gemfile.lock` does and with most of the dependencies being pulled in by the metagems then it's quite possible for the `Gemfile` to not update between releases. We'll need to replace this guard with something a bit less lightweight like a `bundle check` after the changes have been written to disk.

**Comment by scotje** [comment]
Ah yes, I think there might be a Jira ticket about this issue, let me see if I can find it.
