### ISSUE TITLE
puppet 7 dependency problems

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/pdk#931]
**Describe the bug**
When puppet 7 was released new modules use the latest puppet version which is now puppet 7.  This is causing an issue with downstream modules and when switching puppet versions the Gemfile can't unlock the version since it is a major version.

**To Reproduce**
```
pdk new module test
pdk validate or pdk bundle exec rake <command>
```
or

`rspec ./spec/acceptance/bundle_spec.rb:69 `

**Expected behavior**
No errors or pdk would switch to the newer puppet version. 

**Additional context**
```
pdk (INFO): Using Ruby 2.6.6
       pdk (INFO): Using Puppet 6.19.1
       Bundler::GemNotFound: You have requested:
         puppet = 6.19.1
       
       The bundle currently has puppet locked at 7.0.0.
       Try running `bundle update puppet`
       
       If you are updating multiple gems in your Gemfile at once,
       try passing them all to `bundle update`
         /home/gitpod/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/resolver.rb:287:in `block in verify_gemfile_dependencies_are_found!'
         /home/gitpod/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/resolver.rb:255:in `each'
         /home/gitpod/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/resolver.rb:255:in `verify_gemfile_dependencies_are_found!'
         /home/gitpod/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/resolver.rb:49:in `start'
         /home/gitpod/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/resolver.rb:22:in `resolve'
         /home/gitpod/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:258:in `resolve'
         /home/gitpod/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:170:in `specs'
         /home/gitpod/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:237:in `specs_for'
         /home/gitpod/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:226:in `requested_specs'
         /home/gitpod/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:108:in `block in definition_method'
         /home/gitpod/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:20:in `setup'
         /home/gitpod/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler.rb:107:in `setup'
         /home/gitpod/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/setup.rb:20:in `<top (required)>'
         /home/gitpod/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         /home/gitpod/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
       /bin/sh -c pdk\ bundle\ exec\ puppet-lint\ init.pp
       bundler: failed to load command: puppet-lint (/home/gitpod/.pdk/cache/ruby/2.6.0/bin/puppet-lint)
```

**Comment by DavidS** [comment]
This is fixed in the latest nightlies and will be released as PDK2.0 soon.

```
david@zion:/tmp/test$ pdk validate
pdk (INFO): Using Ruby 2.7.2
pdk (INFO): Using Puppet 7.3.0
pdk (INFO): Running all available validators...
pdk (INFO): Validator 'puppet-syntax' skipped for '/tmp/test'. No files matching '["**/*.pp"]' found to validate.
pdk (INFO): Validator 'puppet-lint' skipped for '/tmp/test'. No files matching '["**/*.pp"]' found to validate.
pdk (INFO): Validator 'puppet-epp' skipped for '/tmp/test'. No files matching '["**/*.epp"]' found to validate.
pdk (INFO): Validator 'task-metadata-lint' skipped for '/tmp/test'. No files matching '["tasks/*.json"]' found to validate.
┌ [✔] Running metadata validators ...
├── [✔] Checking metadata syntax (metadata.json tasks/*.json).
```
